### ISSUE TITLE
Using both skip and order derive macros causes proc-macro derive panicked error

### ISSUE THREAD

**Issue by rphillips-nz** [zhiburt/tabled#260]
Here's a minimal test case:

```
#[derive(Tabled)]
pub struct Example {
    #[tabled(skip)]
    pub id: usize,
    #[tabled(order = 0)]
    pub name: String,
    #[tabled(order = 1)]
    pub details: String,
}
```

Here's the error:

```
error: proc-macro derive panicked ​rustc
--> src/example.rs:25:10
   |
25 | #[derive(Tabled)]
   |          ^^^^^^
   |
   = help: message: index out of bounds: the len is 2 but the index is 2
```

Doesn't seem to be any issue if I remove either the order or skip macros, but it would be useful to use them together.

Let me know if I'm doing something wrong here.

**Comment by rphillips-nz** [comment]
I've worked around it with `Disable::column` instead. That seems to conflict with `Width::wrap(120)` though, appears to calculate the width with the disabled/hidden columns, then hide them after that. Results in a table narrower than configured.

**Comment by zhiburt** [comment]
Hi @rphillips-nz 

Thanks for report.

Must be fixed in master.
But I think it won't be published on crates.io for a few weeks.
(I've being doing quite a massive refactoring and I'd like it to be merged too).

In a mean time you can update your `Cargo.toml` to.

```toml
tabled = { git = "https://github.com/zhiburt/tabled", rev = "0f73f2d3a0f892ba623d7ba01cb77b5aaebab10f" }
```

> I've worked around it with Disable::column instead. That seems to conflict with Width::wrap(120) though, appears to calculate the width with the disabled/hidden columns, then hide them after that. Results in a table narrower than configured.

That's interesting but I tend to believe it should not be the case.
Could you provide a reproducible?

Take care.

**Comment by rphillips-nz** [comment]
Hey, no worries @zhiburt, thanks for the great library!

I can confirm the issue is fixed when using the commit above.

The second issue still exists though, I've made a small file to demonstrate the issue - I'll create a new issue for that with the details.
